services:
  app:
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src:/app
    environment:
      SELENIUM_HUB_URL: http://selenium:4444/wd/hub
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm
