services:
  app:
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./src:/app

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm
